name: Package VS Code Extension

on:
  push:
    tags:
      - "vscode-v*.*.*"

permissions:
  contents: write
  discussions: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm" # 开启 pnpm 缓存，加速构建

      - name: Install dependencies
        run: pnpm install

      - name: Build Repository Packages
        run: pnpm run build

      - name: Package Extension
        run: pnpm run pack

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "extension/vscode-extension/*.vsix"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install vsce
        run: pnpm install -g @vscode/vsce

      - name: Publish to Visual Studio Code Marketplace
        run: pnpm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
